#!/usr/bin/env python3
"""
批量汉化 IT-tools 所有工具组件
扫描所有 .vue 文件，提取需要汉化的英文字符串并替换为中文
"""
import os
import re
from pathlib import Path

# 通用英汉翻译映射
TRANSLATIONS = {
    # 按钮和操作
    'Copy': '复制',
    'Copy to clipboard': '复制到剪贴板',
    'Copied': '已复制',
    'Copied to clipboard': '已复制到剪贴板',
    'Clear': '清除',
    'Clear all': '全部清除',
    'Reset': '重置',
    'Generate': '生成',
    'Convert': '转换',
    'Download': '下载',
    'Upload': '上传',
    'Upload a file': '上传文件',
    'Upload file': '上传文件',
    'Upload image': '上传图片',
    'Import': '导入',
    'Export': '导出',
    'Save': '保存',
    'Submit': '提交',
    'Cancel': '取消',
    'Close': '关闭',
    'Refresh': '刷新',
    'Swap': '交换',
    'Select': '选择',
    'Select all': '全选',
    'Deselect all': '取消全选',
    'Add': '添加',
    'Remove': '移除',
    'Delete': '删除',
    'Edit': '编辑',
    'View': '查看',
    'Show': '显示',
    'Hide': '隐藏',
    'Toggle': '切换',
    'Expand': '展开',
    'Collapse': '折叠',
    'Sort': '排序',
    'Filter': '筛选',
    'Search': '搜索',
    'Load': '加载',
    'Loading': '加载中...',
    'Processing': '处理中...',
    'Calculating': '计算中...',
    'Running': '运行中...',
    'Stop': '停止',
    'Pause': '暂停',
    'Resume': '继续',
    'Restart': '重新开始',
    'Start': '开始',
    'Finish': '完成',
    'Done': '完成',
    'Success': '成功',
    'Error': '错误',
    'Warning': '警告',
    'Info': '信息',
    'Result': '结果',
    'Results': '结果',
    'Output': '输出',
    'Input': '输入',
    'Value': '值',
    'Name': '名称',
    'Description': '描述',
    'Type': '类型',
    'Status': '状态',
    'Action': '操作',
    'Actions': '操作',
    'Options': '选项',
    'Settings': '设置',
    'Configuration': '配置',
    'Properties': '属性',
    'Details': '详情',
    'More': '更多',
    'Less': '更少',
    'Previous': '上一个',
    'Next': '下一个',
    'Back': '返回',
    'Forward': '前进',
    'Home': '首页',
    'Menu': '菜单',
    'Help': '帮助',
    'About': '关于',
    'Version': '版本',
    'Author': '作者',
    'Date': '日期',
    'Time': '时间',
    'Size': '大小',
    'Length': '长度',
    'Count': '数量',
    'Total': '总计',
    'Sum': '求和',
    'Average': '平均值',
    'Min': '最小值',
    'Max': '最大值',
    'Range': '范围',
    'Format': '格式',
    'Language': '语言',
    'Theme': '主题',
    'Dark mode': '深色模式',
    'Light mode': '浅色模式',
    'Default': '默认',
    'Custom': '自定义',
    'Advanced': '高级',
    'Basic': '基本',
    'Simple': '简单',
    'Complex': '复杂',
    'Example': '示例',
    'Examples': '示例',
    'Sample': '样本',
    'Test': '测试',
    'Try it': '试一试',
    'Preview': '预览',
    'History': '历史',
    'Recent': '最近',
    'Favorites': '收藏',
    'Bookmarks': '书签',
    'Tools': '工具',
    'All tools': '所有工具',
    'Categories': '分类',
    'Category': '分类',
    'Tags': '标签',
    'Popular': '热门',
    'New': '新增',
    'Updated': '已更新',
    'Recommended': '推荐',
    'Related': '相关',
    'Similar': '相似',
    
    # 输入提示
    'Enter text': '输入文本',
    'Enter value': '输入值',
    'Enter a value': '输入一个值',
    'Enter your text': '输入您的文本',
    'Enter your input': '输入您的内容',
    'Paste your text here': '在此粘贴文本',
    'Type something': '输入内容',
    'Input text': '输入文本',
    'Input value': '输入值',
    'Text to convert': '要转换的文本',
    'Text to encode': '要编码的文本',
    'Text to decode': '要解码的文本',
    'Text to hash': '要哈希的文本',
    'Text to encrypt': '要加密的文本',
    'Text to decrypt': '要解密的文本',
    'Your text': '您的文本',
    'Your input': '您的输入',
    'Your content': '您的内容',
    'Your data': '您的数据',
    'Your file': '您的文件',
    'Your string': '您的字符串',
    
    # 输出标签
    'Output text': '输出文本',
    'Output value': '输出值',
    'Result text': '结果文本',
    'Result value': '结果值',
    'Converted text': '转换后的文本',
    'Encoded text': '编码后的文本',
    'Decoded text': '解码后的文本',
    'Hashed text': '哈希后的文本',
    'Encrypted text': '加密后的文本',
    'Decrypted text': '解密后的文本',
    'Generated text': '生成的文本',
    'Generated value': '生成的值',
    'Generated output': '生成的输出',
    'Converted output': '转换后的输出',
    
    # 文件相关
    'File': '文件',
    'Files': '文件',
    'Filename': '文件名',
    'File size': '文件大小',
    'File type': '文件类型',
    'File content': '文件内容',
    'Open file': '打开文件',
    'Save file': '保存文件',
    'Download file': '下载文件',
    'Upload a file': '上传文件',
    'Drop file here': '将文件拖到此处',
    'Drag and drop': '拖放',
    'Drag and drop a file': '拖放文件',
    'Or click to upload': '或点击上传',
    'Browse': '浏览',
    'Browse files': '浏览文件',
    'Choose file': '选择文件',
    'Select file': '选择文件',
    'No file selected': '未选择文件',
    'File not found': '文件未找到',
    'Invalid file': '无效文件',
    'File too large': '文件过大',
    
    # 表单标签
    'Password': '密码',
    'Username': '用户名',
    'Email': '邮箱',
    'Phone': '电话',
    'Address': '地址',
    'Title': '标题',
    'Content': '内容',
    'Message': '消息',
    'Subject': '主题',
    'Body': '正文',
    'From': '从',
    'To': '到',
    'Subject': '主题',
    'Sender': '发送者',
    'Receiver': '接收者',
    'Amount': '金额',
    'Quantity': '数量',
    'Price': '价格',
    'Cost': '成本',
    'Total': '总计',
    'Subtotal': '小计',
    'Tax': '税',
    'Discount': '折扣',
    'Fee': '费用',
    'Rate': '比率',
    'Percentage': '百分比',
    'Number': '数字',
    'Integer': '整数',
    'Float': '浮点数',
    'String': '字符串',
    'Boolean': '布尔值',
    'Array': '数组',
    'Object': '对象',
    'Null': '空值',
    'True': '真',
    'False': '假',
    'Yes': '是',
    'No': '否',
    'On': '开',
    'Off': '关',
    'Enabled': '已启用',
    'Disabled': '已禁用',
    'Active': '激活',
    'Inactive': '未激活',
    'Visible': '可见',
    'Hidden': '隐藏',
    
    # 状态提示
    'Loading...': '加载中...',
    'Processing...': '处理中...',
    'Calculating...': '计算中...',
    'Generating...': '生成中...',
    'Converting...': '转换中...',
    'Uploading...': '上传中...',
    'Downloading...': '下载中...',
    'Saving...': '保存中...',
    'Please wait': '请稍候',
    'Please wait...': '请稍候...',
    'Success!': '成功！',
    'Done!': '完成！',
    'Error!': '错误！',
    'Warning!': '警告！',
    'Invalid input': '无效输入',
    'Invalid value': '无效值',
    'Invalid format': '无效格式',
    'Invalid file': '无效文件',
    'Required field': '必填字段',
    'This field is required': '此字段为必填项',
    'Enter a valid': '请输入有效的',
    'Must be': '必须为',
    'Cannot be empty': '不能为空',
    'Must be at least': '至少需要',
    'Must be at most': '最多只能',
    'Must be between': '必须在',
    'Characters': '个字符',
    'Items': '个项目',
    'Rows': '行',
    'Columns': '列',
    
    # 工具特定
    'Encrypt': '加密',
    'Decrypt': '解密',
    'Encode': '编码',
    'Decode': '解码',
    'Hash': '哈希',
    'Generate hash': '生成哈希',
    'Generate key': '生成密钥',
    'Generate password': '生成密码',
    'Generate token': '生成令牌',
    'Generate UUID': '生成 UUID',
    'Generate random': '生成随机数',
    'Random': '随机',
    'Random number': '随机数',
    'Random string': '随机字符串',
    'Random password': '随机密码',
    'Secret key': '密钥',
    'Private key': '私钥',
    'Public key': '公钥',
    'API key': 'API 密钥',
    'Token': '令牌',
    'Salt': '盐值',
    'Iterations': '迭代次数',
    'Rounds': '轮次',
    'Key size': '密钥大小',
    'Block size': '块大小',
    'IV': '初始向量',
    'Mode': '模式',
    'Algorithm': '算法',
    'Method': '方法',
    'Function': '函数',
    'Parameter': '参数',
    'Parameters': '参数',
    'Arguments': '参数',
    
    # 编码相关
    'Text encoding': '文本编码',
    'Character encoding': '字符编码',
    'Encoding': '编码',
    'Decoding': '解码',
    'Charset': '字符集',
    'Unicode': 'Unicode',
    'ASCII': 'ASCII',
    'UTF-8': 'UTF-8',
    'UTF-16': 'UTF-16',
    'Binary': '二进制',
    'Octal': '八进制',
    'Decimal': '十进制',
    'Hexadecimal': '十六进制',
    'Hex': '十六进制',
    'Oct': '八进制',
    'Dec': '十进制',
    'Bin': '二进制',
    
    # JSON/XML/YAML
    'JSON': 'JSON',
    'XML': 'XML',
    'YAML': 'YAML',
    'TOML': 'TOML',
    'CSV': 'CSV',
    'TSV': 'TSV',
    'JSON path': 'JSON 路径',
    'XPath': 'XPath',
    'Format JSON': '格式化 JSON',
    'Format XML': '格式化 XML',
    'Minify JSON': '压缩 JSON',
    'Minify XML': '压缩 XML',
    'Validate JSON': '验证 JSON',
    'Validate XML': '验证 XML',
    'Parse JSON': '解析 JSON',
    'Parse XML': '解析 XML',
    'JSON to XML': 'JSON 转 XML',
    'XML to JSON': 'XML 转 JSON',
    'YAML to JSON': 'YAML 转 JSON',
    'JSON to YAML': 'JSON 转 YAML',
    'Convert JSON': '转换 JSON',
    'Convert XML': '转换 XML',
    'Pretty print': '美化输出',
    'Indentation': '缩进',
    'Spaces': '空格',
    'Tabs': '制表符',
    
    # 正则表达式
    'Regular expression': '正则表达式',
    'Regex': '正则表达式',
    'Regex pattern': '正则表达式模式',
    'Pattern': '模式',
    'Match': '匹配',
    'Matches': '匹配',
    'Match result': '匹配结果',
    'Match groups': '匹配组',
    'Replace': '替换',
    'Replace with': '替换为',
    'Replace all': '全部替换',
    'Flags': '标志',
    'Case insensitive': '忽略大小写',
    'Global': '全局',
    'Multiline': '多行',
    'Single line': '单行',
    
    # 网络/IP
    'IP address': 'IP 地址',
    'IPv4': 'IPv4',
    'IPv6': 'IPv6',
    'Subnet': '子网',
    'Subnet mask': '子网掩码',
    'CIDR': 'CIDR',
    'Network': '网络',
    'Host': '主机',
    'Port': '端口',
    'Protocol': '协议',
    'Domain': '域名',
    'Hostname': '主机名',
    'URL': 'URL',
    'URI': 'URI',
    'Path': '路径',
    'Query': '查询',
    'Fragment': '片段',
    'HTTP': 'HTTP',
    'HTTPS': 'HTTPS',
    'Method': '方法',
    'GET': 'GET',
    'POST': 'POST',
    'PUT': 'PUT',
    'DELETE': 'DELETE',
    'Header': '请求头',
    'Headers': '请求头',
    'Body': '请求体',
    'Request': '请求',
    'Response': '响应',
    'Status code': '状态码',
    'Content type': '内容类型',
    'User agent': '用户代理',
    'Cookie': 'Cookie',
    'Session': '会话',
    
    # 时间/日期
    'Date': '日期',
    'Time': '时间',
    'DateTime': '日期时间',
    'Timestamp': '时间戳',
    'Unix timestamp': 'Unix 时间戳',
    'Timezone': '时区',
    'Format': '格式',
    'Now': '现在',
    'Today': '今天',
    'Yesterday': '昨天',
    'Tomorrow': '明天',
    'Year': '年',
    'Month': '月',
    'Week': '周',
    'Day': '天',
    'Hour': '小时',
    'Minute': '分钟',
    'Second': '秒',
    'Millisecond': '毫秒',
    'Microsecond': '微秒',
    
    # 图像相关
    'Image': '图像',
    'Width': '宽度',
    'Height': '高度',
    'Size': '尺寸',
    'Color': '颜色',
    'Background': '背景',
    'Foreground': '前景',
    'Opacity': '透明度',
    'Alpha': '透明度',
    'RGB': 'RGB',
    'RGBA': 'RGBA',
    'HSL': 'HSL',
    'HSV': 'HSV',
    'HEX': 'HEX',
    'QR Code': '二维码',
    'Generate QR Code': '生成二维码',
    'Barcode': '条形码',
    
    # 文本处理
    'Text': '文本',
    'String': '字符串',
    'Character': '字符',
    'Word': '单词',
    'Sentence': '句子',
    'Paragraph': '段落',
    'Line': '行',
    'Line break': '换行',
    'Newline': '换行',
    'Space': '空格',
    'Tab': '制表符',
    'Whitespace': '空白字符',
    'Uppercase': '大写',
    'Lowercase': '小写',
    'Capitalize': '首字母大写',
    'Title case': '标题格式',
    'Sentence case': '句子格式',
    'Reverse': '反转',
    'Sort': '排序',
    'Sort ascending': '升序排序',
    'Sort descending': '降序排序',
    'Unique': '去重',
    'Duplicate': '重复',
    'Count': '计数',
    'Count characters': '字符计数',
    'Count words': '单词计数',
    'Count lines': '行数计数',
    'Word count': '单词数',
    'Character count': '字符数',
    'Line count': '行数',
    'Byte count': '字节数',
    'Find': '查找',
    'Find and replace': '查找替换',
    
    # 差异对比
    'Diff': '差异',
    'Difference': '差异',
    'Compare': '比较',
    'Compare texts': '比较文本',
    'Compare files': '比较文件',
    'Original': '原始',
    'Modified': '修改后',
    'Old': '旧',
    'New': '新',
    'Added': '新增',
    'Removed': '删除',
    'Changed': '已更改',
    'Unchanged': '未更改',
    'Left': '左侧',
    'Right': '右侧',
    
    # 生成器相关
    'Generator': '生成器',
    'Placeholder': '占位符',
    'Lorem Ipsum': 'Lorem Ipsum',
    'Generate Lorem Ipsum': '生成 Lorem Ipsum',
    'Random text': '随机文本',
    'Random name': '随机姓名',
    'Random email': '随机邮箱',
    'Random phone': '随机电话',
    'Random address': '随机地址',
    'Random date': '随机日期',
    'Random IP': '随机 IP',
    'Random UUID': '随机 UUID',
    
    # Cron 表达式
    'Cron': 'Cron',
    'Cron expression': 'Cron 表达式',
    'Every minute': '每分钟',
    'Every hour': '每小时',
    'Every day': '每天',
    'Every week': '每周',
    'Every month': '每月',
    'Every year': '每年',
    'Schedule': '计划',
    'Next run': '下次运行',
    'Next runs': '下次运行',
    
    # 加密/安全
    'Security': '安全',
    'Cipher': '密码',
    'Symmetric': '对称',
    'Asymmetric': '非对称',
    'Signature': '签名',
    'Sign': '签名',
    'Verify': '验证',
    'Certificate': '证书',
    'Public': '公钥',
    'Private': '私钥',
    'Key pair': '密钥对',
    
    # Docker
    'Docker': 'Docker',
    'Container': '容器',
    'Image': '镜像',
    'Volume': '卷',
    'Network': '网络',
    'Compose': 'Compose',
    'Dockerfile': 'Dockerfile',
    'docker run': 'docker run',
    'docker-compose': 'docker-compose',
    
    # Git
    'Git': 'Git',
    'Branch': '分支',
    'Commit': '提交',
    'Tag': '标签',
    'Remote': '远程',
    'Repository': '仓库',
    'Merge': '合并',
    'Rebase': '变基',
    'Cherry-pick': '精选',
    'Stash': '暂存',
}

def process_file(file_path):
    """处理单个文件"""
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # 替换所有翻译
    for en, zh in TRANSLATIONS.items():
        # 替换模板中的文本
        content = content.replace(f'>{en}<', f'>{zh}<')
        content = content.replace(f'"{en}"', f'"{zh}"')
        content = content.replace(f"'{en}'", f"'{zh}'")
        content = content.replace(f'placeholder="{en}"', f'placeholder="{zh}"')
        content = content.replace(f"placeholder='{en}'", f"placeholder='{zh}'")
        content = content.replace(f'label="{en}"', f'label="{zh}"')
        content = content.replace(f"label='{en}'", f"label='{zh}'")
        content = content.replace(f'title="{en}"', f'title="{zh}"')
        content = content.replace(f"title='{en}'", f"title='{zh}'")
        content = content.replace(f'alt="{en}"', f'alt="{zh}"')
        content = content.replace(f"alt='{en}'", f"alt='{zh}'")
    
    if content != original:
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

def main():
    src_dir = Path("/home/sgj/pyproject/IT_tools/src/tools")
    
    count = 0
    for file_path in src_dir.rglob("*.vue"):
        if process_file(file_path):
            count += 1
            print(f"✓ {file_path.relative_to(src_dir)}")
    
    print(f"\n✅ 共处理 {count} 个文件")

if __name__ == "__main__":
    main()
