import { Database } from '@vicons/tabler';
import { defineTool } from '../tool';

export const tool = defineTool({
  name: '数据大小转换器',
  path: '/data-size-converter',
  description: '数据存储单位换算，支持Bit/Byte/KB/MB/GB/TB/PB/EB互转，十进制与二进制标准',
  keywords: [
    'data size',
    'storage',
    'byte',
    'bit',
    'kilobyte',
    'megabyte',
    'gigabyte',
    'terabyte',
    'petabyte',
    'exabyte',
    'kibibyte',
    'mebibyte',
    'gibibyte',
    'tebibyte',
    'binary prefix',
    'decimal prefix',
    '转换',
    '数据大小',
    '存储',
    '字节',
    '比特',
    '千字节',
    '兆字节',
    '吉字节',
    '太字节',
    '拍字节',
    '艾字节',
    '单位换算',
    'KB',
    'MB',
    'GB',
    'TB',
    'PB',
    'EB',
    'KiB',
    'MiB',
    'GiB',
    'TiB',
  ],
  component: () => import('./data-size-converter.vue'),
  icon: Database,
  createdAt: new Date('2026-05-26'),
});
